cudnn test and arg to test again if failed on setup

diff --git a/install/cuda_install b/install/cuda_install
--- a/install/cuda_install
+++ b/install/cuda_install
@@ -1,6 +1,6 @@
 #!/usr/bin/bash
 
-cuda() {
+cuda_install() {
   wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
   sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
   wget https://developer.download.nvidia.com/compute/cuda/12.6.2/local_installers/cuda-repo-wsl-ubuntu-12-6-local_12.6.2-1_amd64.deb
@@ -10,7 +10,7 @@ cuda() {
   sudo apt-get -y install cuda-toolkit-12-6
 }
 
-cudnn() {
+cudnn_install() {
   wget https://developer.download.nvidia.com/compute/cudnn/9.4.0/local_installers/cudnn-local-repo-ubuntu2404-9.4.0_1.0-1_amd64.deb
   sudo dpkg -i cudnn-local-repo-ubuntu2404-9.4.0_1.0-1_amd64.deb
   sudo cp /var/cudnn-local-repo-ubuntu2404-9.4.0/cudnn-*-keyring.gpg /usr/share/keyrings/
@@ -18,3 +18,35 @@ cudnn() {
   sudo apt-get -y install cudnn
   sudo apt-get -y install cudnn-cuda-12
 }
+
+verify_cudnn_install() {
+  cp /usr/src/cudnn_samples_v9/ $HOME/Downloads
+  cd $HOME/Downloads/cudnn_samples_v9/mnistCUDNN && make clean && make
+  compile=$(./mnistCUDNN)
+  passed=$compile | tail -n 1
+  if [ "$passed" = "Test passed!" ]; then
+    echo "Tests for CUDNN Install has passed!"
+  else
+    echo "Tests for CUDNN Failed!"
+    echo "Please see below log and do the needful"
+    echo "Once fixed please pass '1' as argument to the script to test."
+    echo "$compile"
+  fi
+}
+
+args=$1
+if [ $# -eq 0 ]; then
+  echo "Starting CUDA/CUDNN Setup"
+  cuda_install
+  cudnn_install
+  verify_cudnn_install
+  echo "Completed CUDA/CUDNN Setup"
+else
+  if [[ $args -eq 1 ]]; then
+    echo "Starting the test"
+    verify_cudnn_install
+  else
+    echo "Unrecognized arg $arg"
+    exit 1
+  fi
+fi
